#!/bin/bash

input_1="$1"

if [[ $input_1 = "" ]]; then
	printf "please give a file path: poemaker <filename>\n"
	exit 1
fi

title="$(head -n 1 $1)"
poem_content="$(sed -E '1d;:a;N;$!ba;s/\r{0,1}\n/\\n/g' ./$1)"

colors=( "#00695c" \
	"#00838f" \
	"#0277bd" \
	"#1565c0" \
	"#283593" \
	"#2e7d32" \
	"#37474f" \
	"#424242" \
	"#4527a0" \
	"#4e342e" \
	"#558b2f" \
	"#6a1b9a" \
	"#ad1457" \
	"#c62828" \
	"#d84315" \
	"#ef6c00" \
	"#f9a825" \
	"#ff8f00" \
)

random_color=$(shuf -i 0-17 -n 1)
date="$(date '+%y.%-m.%-d')"

create_contents() {
	convert -size 1000x1000 \
		canvas:"${colors[$random_color]}" \
		./.bg.png

	convert -background transparent \
		-fill "#ffffff" \
		-font "$HOME"/.local/share/fonts/ReadexPro-Bold.ttf \
		-pointsize 60 \
		label:"$title" \
		./.title.png

	convert -background transparent \
		-fill "#ffffff" \
		-font "$HOME"/.local/share/fonts/ReadexPro-Light.ttf \
		-interline-spacing -4 \
		-pointsize 40 \
		label:"$poem_content" \
		./.poem_content.png

	convert -background transparent \
		-fill "#ffffff" \
		-font "$HOME"/.local/share/fonts/ReadexPro-SemiBold.ttf \
		-pointsize 50 \
		label:"$date" \
		./.date.png
}

merge_contents() {
	composite -geometry +40+25 \
	./.title.png ./.bg.png "./$title.png"
	composite -geometry +40+120 \
	./.poem_content.png "./$title.png" "./$title.png"
	composite -gravity SouthEast \
	-geometry +40+28 \
	./.date.png "./$title.png" "./$title.png"
}

create_contents
merge_contents
rm ./.bg.png ./.title.png ./.poem_content.png ./.date.png
